/**
 * Generates components/dynamic/utils/CodeBlocksMeta.ts from BlockRegistry.
 * Run with: npx tsx scripts/generate-block-meta.ts
 */
import { writeFileSync } from 'fs'
import { join } from 'path'
import { getCodeBlocks } from '../components/dynamic/utils/BlockRegistry'

const blocks = getCodeBlocks()

const entries = blocks.map((b) => {
  const { Component: _c, ...meta } = b
  return `  {
    type: ${JSON.stringify(meta.type)},
    label: ${JSON.stringify(meta.label)},
    category: ${JSON.stringify(meta.category)},
    description: ${JSON.stringify(meta.description)},
    defaultProps: ${JSON.stringify(meta.defaultProps, null, 2).replace(/\n/g, '\n    ')},
    schema: ${JSON.stringify(meta.schema, null, 2).replace(/\n/g, '\n    ')},
  }`
})

const output = `import type { FieldSchema } from '../types'

export interface CodeBlockMeta {
  type: string
  label: string
  category: string
  description: string
  schema: Record<string, FieldSchema>
  defaultProps: Record<string, unknown>
}

// Auto-generated by scripts/generate-block-meta.ts — do not edit manually.
// Re-run the script when blocks are added or modified.
export const CODE_BLOCK_META: CodeBlockMeta[] = [
${entries.join(',\n')}
]
`

const outPath = join(__dirname, '../components/dynamic/utils/CodeBlocksMeta.ts')
writeFileSync(outPath, output, 'utf-8')
console.log(`✓ Wrote ${blocks.length} blocks to CodeBlocksMeta.ts`)
