import {
  faBriefcase, faGraduationCap, faUniversity, faCode, faRocket,
  faStar, faBuilding, faMedal, faTrophy, faAward, faCertificate,
  faChartLine, faLaptopCode, faAtom, faSchool, faFlask, faHeart,
  faCog, faTools, faWrench, faHammer, faLeaf, faHandshake, faLightbulb,
  faUsers, faGlobe, faLayerGroup, faMicroscope, faPenRuler, faShieldHalved,
  faDatabase, faServer, faCloud, faNetworkWired, faBolt, faFire,
  faFlagCheckered, faMapPin, faClock, faCalendarDays,
  faKey, faStream, faMoneyBill, faVial, faArchway,
  faTerminal, faCubes, faPuzzlePiece, faGears, faMicrochip,
} from '@fortawesome/free-solid-svg-icons'
import {
  faHtml5, faCss3, faReact, faNodeJs, faPhp, faJava, faLinux, faFigma,
  faPython, faDocker, faGit, faGithub, faAws, faVuejs, faAngular,
  faSwift, faRust, faJs, faSass, faWordpress, faLaravel,
} from '@fortawesome/free-brands-svg-icons'
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core'

export interface IconOption {
  name: string
  icon: IconDefinition
}

export const ICON_OPTIONS: IconOption[] = [
  // Brand icons
  { name: 'react',      icon: faReact },
  { name: 'html5',      icon: faHtml5 },
  { name: 'css3',       icon: faCss3 },
  { name: 'nodejs',     icon: faNodeJs },
  { name: 'php',        icon: faPhp },
  { name: 'java',       icon: faJava },
  { name: 'python',     icon: faPython },
  { name: 'js',         icon: faJs },
  { name: 'docker',     icon: faDocker },
  { name: 'git',        icon: faGit },
  { name: 'github',     icon: faGithub },
  { name: 'aws',        icon: faAws },
  { name: 'linux',      icon: faLinux },
  { name: 'figma',      icon: faFigma },
  { name: 'vuejs',      icon: faVuejs },
  { name: 'angular',    icon: faAngular },
  { name: 'swift',      icon: faSwift },
  { name: 'rust',       icon: faRust },
  { name: 'sass',       icon: faSass },
  { name: 'wordpress',  icon: faWordpress },
  { name: 'laravel',    icon: faLaravel },
  // Solid icons
  { name: 'briefcase',      icon: faBriefcase },
  { name: 'graduation-cap', icon: faGraduationCap },
  { name: 'university',     icon: faUniversity },
  { name: 'school',         icon: faSchool },
  { name: 'code',           icon: faCode },
  { name: 'laptop-code',    icon: faLaptopCode },
  { name: 'building',       icon: faBuilding },
  { name: 'rocket',         icon: faRocket },
  { name: 'star',           icon: faStar },
  { name: 'medal',          icon: faMedal },
  { name: 'trophy',         icon: faTrophy },
  { name: 'award',          icon: faAward },
  { name: 'certificate',    icon: faCertificate },
  { name: 'chart-line',     icon: faChartLine },
  { name: 'atom',           icon: faAtom },
  { name: 'flask',          icon: faFlask },
  { name: 'microscope',     icon: faMicroscope },
  { name: 'heart',          icon: faHeart },
  { name: 'handshake',      icon: faHandshake },
  { name: 'lightbulb',      icon: faLightbulb },
  { name: 'users',          icon: faUsers },
  { name: 'globe',          icon: faGlobe },
  { name: 'layer-group',    icon: faLayerGroup },
  { name: 'pen-ruler',      icon: faPenRuler },
  { name: 'shield-halved',  icon: faShieldHalved },
  { name: 'database',       icon: faDatabase },
  { name: 'server',         icon: faServer },
  { name: 'cloud',          icon: faCloud },
  { name: 'network-wired',  icon: faNetworkWired },
  { name: 'cog',            icon: faCog },
  { name: 'tools',          icon: faTools },
  { name: 'wrench',         icon: faWrench },
  { name: 'hammer',         icon: faHammer },
  { name: 'bolt',           icon: faBolt },
  { name: 'fire',           icon: faFire },
  { name: 'leaf',           icon: faLeaf },
  { name: 'flag-checkered', icon: faFlagCheckered },
  { name: 'map-pin',        icon: faMapPin },
  { name: 'clock',          icon: faClock },
  { name: 'calendar',       icon: faCalendarDays },
  { name: 'key',            icon: faKey },
  { name: 'stream',         icon: faStream },
  { name: 'money-bill',     icon: faMoneyBill },
  { name: 'vial',           icon: faVial },
  { name: 'archway',        icon: faArchway },
  { name: 'terminal',       icon: faTerminal },
  { name: 'cubes',          icon: faCubes },
  { name: 'puzzle-piece',   icon: faPuzzlePiece },
  { name: 'gears',          icon: faGears },
  { name: 'microchip',      icon: faMicrochip },
]

export const ICON_MAP: Record<string, IconDefinition> = Object.fromEntries(
  ICON_OPTIONS.map(({ name, icon }) => [name, icon])
)
